const actionType = {
    LOGIN: 'login/LOGIN',
    LOGIN_FAILURE: 'login/LOGIN_FAILURE',
    LOGIN_SUCCESS: 'login/LOGIN_SUCCESS',
    LOGIN_RESET: 'login/LOGIN_RESET',

    VALIDATE_TOKEN: 'login/VALIDATE_TOKEN',
    VALIDATE_TOKEN_FAILURE: 'login/VALIDATE_TOKEN_FAILURE',
    VALIDATE_TOKEN_SUCCESS: 'login/VALIDATE_TOKEN_SUCCESS',
    VALIDATE_TOKEN_RESET: 'login/VALIDATE_TOKEN_RESET',


    CHANGE_SHOP: 'login/CHANGE_SHOP',
    CHANGE_SHOP_FAILURE: 'login/CHANGE_SHOP_FAILURE',
    CHANGE_SHOP_SUCCESS: 'login/CHANGE_SHOP_SUCCESS',
    CHANGE_SHOP_RESET: 'login/CHANGE_SHOP_RESET',

    CHANGE_DATA_USER: 'login/CHANGE_DATA_USER',

    LOGOUT: 'login/LOGOUT',
    LOGOUT_FAILURE: 'login/LOGOUT_FAILURE',
    LOGOUT_SUCCESS: 'login/LOGOUT_SUCCESS',
    LOGOUT_RESET: 'login/LOGOUT_RESET',

    CHANGE_PWD_FIRST_LOGIN: 'login/CHANGE_PWD_FIRST_LOGIN',
};

export default actionType;