const paths = {
    DASHBOARD: '/dashboard',
    REPORTS: '/reports',
    DOMAINS: '/domain',
    USERS: '/user',
    CORPORATIONS: '/corporations',
    SHOPS: '/shop',
    CUSTOMERS: '/customer',
    SUPPLIER: '/supplier',
    SALES: '/sales',
    ROUTE: '/route',
    ACCOUNT: '/account',
    PURCHASES: '/purchases',
    STOCK: '/stock',
    SIGNIN: '/sign-in',
    PRODUCTS: '/products',
    VEHICLE: '/vehicle',
    PAYMENT_METHODS: '/payment_methods',
    DRIVER: '/driver',
    CASH_BOX: '/cash_box',
    BIKERS: '/bikers',
    ASSISTANT: '/assistant',
};

export default paths;
